---
.gitignore:
  required:
    - ---.project

appveyor.yml:
  use_litmus: true
  matrix_extras:
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: yes
      TARGET_HOST: localhost
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: yes
      TARGET_HOST: localhost
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  dist: trusty
  user: puppet
  secure: ""
  branches:
    - release
  includes:
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=deb_puppet5
      rvm: 2.5.1
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_deb]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:serial
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=deb_puppet6
      rvm: 2.5.1
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_deb]'
      - bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:serial
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el_puppet5
      rvm: 2.5.1
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el]'
      - bundle exec rake 'litmus:install_agent[puppet5]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:serial
      services: docker
      sudo: required
      stage: acceptance
    -
      bundler_args:
      dist: trusty
      env: PLATFORMS=el_puppet6
      rvm: 2.5.1
      before_script:
      - bundle exec rake 'litmus:provision_list[waffle_el]'
      - bundle exec rake 'litmus:install_agent[puppet6]'
      - bundle exec rake litmus:install_module
      script:
      - bundle exec rake litmus:acceptance:serial
      services: docker
      sudo: required
      stage: acceptance

Gemfile:
  use_litmus: true
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"

Rakefile:
  requires:
    - puppet_pot_generator/rake_tasks

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
