---
dist: xenial
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - "# Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
  - "# See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
  - '[ -z "$RUBYGEMS_VERSION" ] || gem update --system $RUBYGEMS_VERSION'
  - gem --version
  - bundle -v
script:
  - 'SIMPLECOV=yes bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
stages:
  - static
  - spec
  - acceptance
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop syntax lint metadata_lint"
      stage: static
    -
      env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
    -
      env: PUPPET_GEM_VERSION="~> 6.0" CHECK=parallel_spec
      rvm: 2.5.3
      stage: spec
    -
      before_script: ["bundle exec rake 'litmus:provision_list[waffle_deb]'", "bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=deb_puppet5
      rvm: 2.5.1
      script: ["bundle exec rake litmus:acceptance:serial"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[waffle_deb]'", "bundle exec bolt command run 'apt-get install wget -y' --inventoryfile inventory.yaml --nodes='localhost*'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=deb_puppet6
      rvm: 2.5.1
      script: ["bundle exec rake litmus:acceptance:serial"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[waffle_el]'", "bundle exec rake 'litmus:install_agent[puppet5]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=el_puppet5
      rvm: 2.5.1
      script: ["bundle exec rake litmus:acceptance:serial"]
      services: docker
      stage: acceptance
      sudo: required
    -
      before_script: ["bundle exec rake 'litmus:provision_list[waffle_el]'", "bundle exec rake 'litmus:install_agent[puppet6]'", "bundle exec rake litmus:install_module"]
      bundler_args: 
      env: PLATFORMS=el_puppet6
      rvm: 2.5.1
      script: ["bundle exec rake litmus:acceptance:serial"]
      services: docker
      stage: acceptance
      sudo: required
branches:
  only:
    - master
    - /^v\d/
    - release
notifications:
  email: false
  slack:
    secure: EtyvcUX7n4eFSO5B2h5nH0PJXRJv4FpuJ2SjHuMjALlsHiYrNL2JA+t/PXF6xPLvWNs+pH2rWwBAXDzgR4Ltj3eiaN4UuM8Dvt+KmQ1h0ez2eATpmN47aZ4TueiMkSiUVzWT9aSZa85lS1nr9VcRuFLmTLVU1FH01Uu//5uiZkbcU5kODlkFYsT1/oUXEAA2U6MQdANRKYD2RFHb/M21RoV0rIjLy16cwOuHiXMvIb0tzWQOfauKI9byofK/oq+uryLmbAHeT3IYGCqggvrMVf7D6IsQgit83BRWR7hXKd6HNZUbdZvUEdRMtFhu3jH86BVrObNKZ/6aO5/e49yzsaZMXIvNjvQBs3na7TP7GuaDpDAasjaRUgNyGX3v+ALATFScL7RmdBngmLOVCyjPQ3BS5xtiiq7lnbNBPHD+pWaX+0KLcLtwFWUIz15XkLVTfWZ3LafuwSGiOtA5FK3NiuXxtHr6sLJIw5GMj4K0skUsGUR4P7V+fk4iS+nJtqd4wrZRgCEHUFhkPUfkR3c8LYfqqpe5EdFAK2ZBwqy5z3o7jtSLf4Q786OfMp+v9KcqDREMCkIy+zKafpVmSKV77zYZUdJ+F7rNikqWwqIXU9YFNyeWvIKoikc/YfLY0kXFOVU4yIcWS2lmtzS/tSGy0QS1E0PrbvqJ2Ubrk6djJEY=
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
